# Generated by Django 5.0 on 2024-12-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('wing', 'Wing'), ('body', 'Body'), ('tail', 'Tail'), ('avionics', 'Avionics')], max_length=20)),
                ('uav_type', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=20)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('production_date', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('produced_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teammember')),
            ],
            options={
                'unique_together': {('type', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='UAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('tb2', 'TB2'), ('tb3', 'TB3'), ('akinci', 'AKINCI'), ('kizilelma', 'KIZILELMA')], max_length=20)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('assembly_date', models.DateTimeField(auto_now_add=True)),
                ('assembled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.teammember')),
                ('avionics', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uav_avionics', to='production.part')),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uav_body', to='production.part')),
                ('tail', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uav_tail', to='production.part')),
                ('wing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uav_wing', to='production.part')),
            ],
        ),
    ]
